<?php
/**
 * TWD_SK_Elementor: the two Elementor Theme Builder templates, as importable JSON.
 *
 * Each template is one full-width container holding one Shortcode widget, [twd_header] or
 * [twd_footer]. Everything about the header and footer (links, words, variant) lives in the
 * plugin, so the same two templates serve every site. A base site imports them once, then sets
 * each template's display condition to the entire site.
 *
 * The files are generated by bin/build-elementor-templates.php into starters/elementor/ and a
 * test fails if they differ. Whether Elementor Pro accepts them on import has to be checked
 * on a real site (see BUILD-LOG.md).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class TWD_SK_Elementor {

	const FORMAT_VERSION = '0.4';

	private static function zero_box() {
		return array( 'unit' => 'px', 'top' => '0', 'right' => '0', 'bottom' => '0', 'left' => '0', 'isLinked' => true );
	}

	/**
	 * @param string $type  header or footer
	 * @param string $title The template's name in the Theme Builder.
	 * @param string $shortcode
	 * @param string $id_seed Fixed seed so the ids never change between builds.
	 */
	private static function template( $type, $title, $shortcode, $id_seed ) {
		return array(
			'content'       => array(
				array(
					'id'       => substr( md5( $id_seed . 'container' ), 0, 7 ),
					'elType'   => 'container',
					'settings' => array(
						'content_width'  => 'full',
						'flex_direction' => 'column',
						'padding'        => self::zero_box(),
						'margin'         => self::zero_box(),
					),
					'elements' => array(
						array(
							'id'         => substr( md5( $id_seed . 'widget' ), 0, 7 ),
							'elType'     => 'widget',
							'widgetType' => 'shortcode',
							'settings'   => array( 'shortcode' => $shortcode ),
							'elements'   => array(),
						),
					),
					'isInner'  => false,
				),
			),
			'page_settings' => array(),
			'version'       => self::FORMAT_VERSION,
			'title'         => $title,
			'type'          => $type,
		);
	}

	public static function header_template() {
		return self::template( 'header', 'TWD Header', '[twd_header]', 'twd-sk-header' );
	}

	public static function footer_template() {
		return self::template( 'footer', 'TWD Footer', '[twd_footer]', 'twd-sk-footer' );
	}

	/** file name => JSON text, exactly as written to starters/elementor/. */
	public static function files() {
		$flags = JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;
		return array(
			'twd-header.json' => json_encode( self::header_template(), $flags ) . "\n",
			'twd-footer.json' => json_encode( self::footer_template(), $flags ) . "\n",
		);
	}
}
